galleries:
  - image: /images/product-07.jpg
    video: none

  - image: /images/product-15.jpg
    video: none

  - image: /images/product-16.jpg
    video: none

  - image: /images/product-17.jpg
    video: https://www.youtube.com/watch?v=6v2L2UGZJAM


image-box:
  - image: /images/single-product-01.jpg
  - image: /images/single-product-02.jpg
  - image: /images/single-product-03.jpg
  - image: /images/single-product-04.jpg

products:
  - image: /images/product-03.jpg
    title: Facial cleanser
    price: $29.00
    label: none
    reviews: 2947
    url: /product-page-01.html

  - image: /images/product-04.jpg
    title: Bio-shroom Rejuvenating Serum
    price: $29.00
    label: none
    reviews: 2947
    url: /product-page-01.html

  - image: /images/product-09.jpg
    title: Coffee Bean Caffeine Eye Cream
    price: $29.00
    sale: $39.00
    label: sale
    reviews: 2947
    url: /product-page-01.html

  - image: /images/product-08.jpg
    title: Coffee Bean Caffeine Eye Cream
    price: $29.00
    label: new
    reviews: 2947
    url: /product-page-01.html
