galleries:
  - image: /images/product-07.jpg
  - image: /images/product-15.jpg
  - image: /images/product-16.jpg
  - image: /images/product-17.jpg

togheter:
  - image: /images/product-07.jpg
    data-name: Facial cleanser

  - image: /images/product-09.jpg
    data-name: Coffee Bean Caffeine Eye Cream

  - image: /images/product-08.jpg
    data-name: Coffee Bean Caffeine Eye Cream