galleries:
  - image: /images/product-07.jpg
  - image: /images/product-15.jpg
  - image: /images/product-23.jpg
  - image: /images/product-06.jpg
  - image: /images/product-05.jpg
  - image: /images/product-24.jpg