galleries:
  - image: /images/product-05.jpg
  - image: /images/product-21.jpg
  - image: /images/product-22.jpg
  - image: /images/product-20.jpg

products:
  - image: /images/product-06.jpg
    title: Facial cleanser
    price: $29.00
    sale: $39.00
    label: sale
    reviews: 2947
    url: /product-page-01.html

  - image: /images/product-08.jpg
    title: Bio-shroom Rejuvenating Serum
    price: $29.00
    label: none
    reviews: 2947
    url: /product-page-01.html

  - image: /images/product-09.jpg
    title: Coffee Bean Caffeine Eye Cream
    price: $29.00
    label: none
    reviews: 2947
    url: /product-page-01.html

  - image: /images/product-11.jpg
    title: Coffee Bean Caffeine Eye Cream
    price: $29.00
    sale: $39.00
    label: sale
    reviews: 2947
    url: /product-page-01.html